# Dependencies
markdown: kramdown
highlighter: rouge

# Gems
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-redirect-from
  - jekyll-seo-tag

# Settings
color: '#fab005'
exclude:
  [
    CNAME,
    README.md,
    NOTES.md,
    LICENSE.md,
    .gitignore,
    package.json,
    _js,
    _scss,
    _images,
    gulpfile.js,
    gulpconfig.js,
    node_modules,
    gemfile,
    Gemfile.lock,
  ]
permalink: /:title/
compress_html:
  clippings: all
  comments: all
dark_theme: true

# Site meta
title: INFIMATH
tagline: 'Make Math Simple'
description: 'Mathematics videos without distraction.'
keywords: 'connor, bär, designer, traveller, code, jekyll, developer, theme'
url: https://127.0.0.1:4000
# baseurl:
assets: /assets
images: /images
image: index-large.jpg
logo: /assets/icons/144.png

author:
  name: Sandeep Suman
  bio: Hi, I'm Samdeep, the author of this website. Nice to meet you!
  image: author
  url: https://sandeepsuman.com
  email: ssuman@infimath.com
  twitter: ssumanss

social:
  twitter: https://twitter.com/ssumanss
  facebook: https://facebook.com/ssumantmbu

version: 2.0.0

# github:
#   repo: https://github.com/connor-baer/summer

# Integrations
# typekit:              fcv7rfe

google_fonts:
  Overpass: 400, 600, 800

# google_analytics_key: UA-37412525-4
# google_site_verification: Z-pc_HPc4XNBz8xg1fgtxO2MSIYLirZc2jWTNq0bJyM

# Content
excerpt_separator: <!-- Read more -->

navigation:
  Sandeep Suman: https://sandeepsuman.com
  CSIR NET Solution: https://csir.infimath.com/
  
external_links:
  CSIR: https://csirnet.nta.nic.in/
  NPTEL: https://nptel.ac.in/

collections:
  basic-real-analysis:
    output: true


defaults:
  - scope:
      path: ''
      type: posts
    values:
      layout: post
      lang: en
      permalink: /news/:title/
  - scope:
      path: ''
      type: "basic-real-analysis"
    values:
      layout: basic-real-analysis
      lang: en
      permalink: /basic-real-analysis/:title/
